image:
  name: hashicorp/terraform:1.6
  entrypoint: [""]

stages:
  - deploy

variables:
  TF_IN_AUTOMATION: "true"
  AWS_DEFAULT_REGION: "$AWS_DEFAULT_REGION"
  AWS_ACCESS_KEY_ID: "$AWS_ACCESS_KEY_ID"
  AWS_SECRET_ACCESS_KEY: "$AWS_SECRET_ACCESS_KEY"

before_script:
  - cd terraform
  - terraform --version
  

deploy:
  stage: deploy
  script:
    - terraform init
    - terraform validate
    - terraform apply -auto-approve
  only:
    - main
