image:
  name: hashicorp/terraform:1.6
  entrypoint: [""]

stages:
  - deploy

before_script:
  - cd terraform
  - terraform --version


variables:
  TF_IN_AUTOMATION: "true"
  AWSAccessKey: "$AWS_ACCESS_KEY_ID"
  AWSSecretKey: "$AWS_SECRET_ACCESS_KEY"
  AWS_DEFAULT_REGION: "$AWS_DEFAULT_REGION"

deploy:
  stage: deploy
  script:
    - terraform init
    - terraform validate
    - terraform apply -auto-approve
  only:
    - main
